### PR TITLE
.gitmodules: revert path local change

### PR DESCRIPTION
**Pull request by glensc**
Revert `.gitmodules` change to local in #266 via 98444d30

Change not mentioned in commit log or PR details, so apparently a mistake.

### CODE REVIEW

**Comment by metsma** [comment]
This change follows same rule like all other components

**Comment by glensc** [comment]
What?

You remove the urls, replace with local paths, meaning the submodules origin url is specific to your personal project setup. Please see the diff and reconsider.

**Comment by metsma** [comment]
https://github.com/open-eid/qdigidoc/blob/master/.gitmodules

**Comment by metsma** [comment]
When github closes down (or changes license or something else) and we migrate to gitlab/stash/bitbucket... then we don't need rewrite history and relative paths keep still working

**Pull request closed without merging**
