### PR TITLE
Make LibDigiDocpp dependency versioned

### LINKED ISSUE #408: 4.2.0.43 compile failure with gcc 8.2
prepare:
```
git checkout v4.2.0
git submodule update
cmake .
make
```

```
[~/rpm/packages/digidoc4-client/DigiDoc4-Client] ➔ make
[  2%] Built target translations_1
[  2%] Automatic MOC for target qtsingleapplication
[  2%] Built target qtsingleapplication_autogen
[  5%] Built target qtsingleapplication
[  6%] Automatic MOC for target qdigidoccommon
[  6%] Built target qdigidoccommon_autogen
[ 27%] Built target qdigidoccommon
[ 27%] Automatic MOC for target qdigidoc4
[ 27%] Built target qdigidoc4_autogen
[ 28%] Automatic MOC for target TSLDownload
[ 28%] Built target TSLDownload_autogen
[ 29%] Built target TSLDownload
[ 30%] Building CXX object client/CMakeFiles/qdigidoc4.dir/Application.cpp.o
/home/users/glen/rpm/packages/digidoc4-client/DigiDoc4-Client/client/Application.cpp:170:7: error: ‘void DigidocConf::setTSUrl(const string&)’ marked ‘override’, but does not override
  void setTSUrl(const std::string &url) override
       ^~~~~~~~
/home/users/glen/rpm/packages/digidoc4-client/DigiDoc4-Client/client/Application.cpp: In destructor ‘virtual Application::~Application()’:
/home/users/glen/rpm/packages/digidoc4-client/DigiDoc4-Client/client/Application.cpp:413:12: warning: possible problem detected in invocation of delete operator: [-Wdelete-incomplete]
  delete d->bar;
            ^~~
/home/users/glen/rpm/packages/digidoc4-client/DigiDoc4-Client/client/Application.cpp:413:12: warning: invalid use of incomplete type ‘class MacMenuBar’
  delete d->bar;
         ~~~^~~
/home/users/glen/rpm/packages/digidoc4-client/DigiDoc4-Client/client/Application.cpp:67:7: note: forward declaration of ‘class MacMenuBar’
 class MacMenuBar;
       ^~~~~~~~~~
/home/users/glen/rpm/packages/digidoc4-client/DigiDoc4-Client/client/Application.cpp:413:12: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
  delete d->bar;
            ^~~
/home/users/glen/rpm/packages/digidoc4-client/DigiDoc4-Client/client/Application.cpp: In static member function ‘static void Application::setConfValue(Application::ConfParameter, const QVariant&)’:
/home/users/glen/rpm/packages/digidoc4-client/DigiDoc4-Client/client/Application.cpp:851:19: error: ‘digidoc::XmlConfCurrent’ {aka ‘class digidoc::XmlConfV2’} has no member named ‘setTSUrl’; did you mean ‘TSUrl’?
   case TSAUrl: i->setTSUrl(v.isEmpty()? std::string() : v.constData()); break;
                   ^~~~~~~~
                   TSUrl
make[2]: *** [client/CMakeFiles/qdigidoc4.dir/build.make:391: client/CMakeFiles/qdigidoc4.dir/Application.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:383: client/CMakeFiles/qdigidoc4.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
[~/rpm/packages/digidoc4-client/DigiDoc4-Client] ➔
```

```
➔ g++ --version
g++ (PLD-Linux) 8.2.0 20181009 (release)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### PR DESCRIPTION
**Pull request by glensc**
Fixes #408

cc @metsma

### CODE REVIEW

**Comment by glensc** [comment]
For this to work `libdigidocpp.pc` needs to provide `Version:`

For me it's empty:

```
➔ cat /usr/lib64/pkgconfig/libdigidocpp.pc
prefix=/usr
exec_prefix=/usr/bin
libdir=/usr/lib64
includedir=/usr/include

Name: libdigidocpp
Description: Libdigidocpp C++ library for handling digitally signed documents
Version:
Libs: -L${libdir} -ldigidocpp
Cflags: -I${includedir}
```

The used `DIGIDOCPP_VERSION` macro doesn't seem to be defined in `libdigidocpp`:

```
[~/rpm/packages/BUILD.x86_64-linux/libdigidocpp-3.13.8(3.8)] ➔ rgrep -r DIGIDOCPP_VERSION .
./etc/Doxyfile.in:41:PROJECT_NUMBER         = @DIGIDOCPP_VERSION@
./src/libdigidocpp.pc.cmake:8:Version: @DIGIDOCPP_VERSION@
[~/rpm/packages/BUILD.x86_64-linux/libdigidocpp-3.13.8(3.8)] ➔
```

**Comment by glensc** [comment]
looks like `DIGIDOCPP_VERSION` was never defined in the project.

at least the [initial commit](https://github.com/open-eid/libdigidocpp/commit/9ebb3305a15fa982bdb7943e7fdeed2269f28759) in git repo already has it unreferenced. i suppose the svn history is not available?

**Comment by metsma** [comment]
It should be probably PROJECT_VERSION
https://cmake.org/cmake/help/v3.13/variable/PROJECT_VERSION.html#variable:PROJECT_VERSION

**Comment by metsma** [comment]
https://github.com/open-eid/libdigidocpp/pull/260

**Comment by glensc** [comment]
hmm. it's not fatal error even the version is not satisfied:

```
-- Found LibDigiDocpp: /usr/lib64/libdigidocpp.so (Required is at least version "3.13.9")
...
➔ grep Ver /usr/lib64/pkgconfig/libdigidocpp.pc
Version: 3.13.8
```

**Pull request merged**
