### PR TITLE
Fix QT version

### PR DESCRIPTION
**Pull request by axelvf**
5.9.1 --> 5.12.7

### CODE REVIEW

**Comment by karl80038** [comment]
QT 5.12.8 should be used instead (the latest version as of writing this comment) as I was unable to compile the code using QT 5.12.7, more on that here: https://github.com/open-eid/DigiDoc4-Client/issues/701, where as the code compiled without any issues using QT 5.12.8.

**Comment by axelvf** [comment]
Thank you @karl80038 for your quick response. I just updated the documentation and prepare_osx_build_environment.sh to use the version 5.12.8 of QT:
image

But now fail on build:
cp: build/qdigidoc4*.zip: No such file or directory
It's strange because this file doesn't change. I'll check it.

**Comment by axelvf** [comment]
@karl80038 Did you try on osx? the reference of #701 is on Windows.

**Comment by metsma** [comment]
I need build Qt outside CI and add to cache. We don't get enough build time for Qt in free CI

**Comment by metsma** [comment]
Can you update macos prepare script openldap to 2.4.50

**Comment by karl80038** [comment]
> @karl80038 Did you try on osx? the reference of #701 is on Windows.

Unfortunately, I don't have any means of access to a modern Mac computer (The only Mac I own is a vintage iBook G4 and that's considered a collector's item). So yes, I compile on a Windows 10 1909 PC running Visual Studio 2019, usually the current version available or sometimes the version that precedes the newest version.

**Comment by axelvf** [comment]
> I need build Qt outside CI and add to cache. We don't get enough build time for Qt in free CI

Need help in this point?

**Comment by metsma** [comment]
> > I need build Qt outside CI and add to cache. We don't get enough build time for Qt in free CI
> 
> Need help in this point?

No its done by my side and travis is green and happy

**Pull request merged**
