### PR TITLE
Include AppStream metainfo.xml

### PR DESCRIPTION
**Pull request by minosimo**
Signed-off-by: Simon Dalzell <simon@oddlypresent.com>

### CODE REVIEW

**Comment by metsma** [comment]
Can you add hint what it does resolve and how it is used. Does it need to be installed somewhere?

**Comment by minosimo** [comment]
This brings the package more in line with the freedesktop XDG spec. The metainfo.xml file gets installed to /usr/share/metainfo, which allows the application to show up in places like Gnome software or KDE Discover, and properly shows the description, icon, screenshots, links to the repo, and changelog. I believe this will also allow users to uninstall the application using eg. gnome-software.

The change to reverse-DNS naming for the .desktop file is also in line with the freedesktop spec.

**Comment by metsma** [comment]
Can you please rebase latest master to fix windows builds.
We need figure out if there is screenshots available in id.ee site, currently it links to your branch content

**Comment by minosimo** [comment]
I found a good screenshot hosted on id.ee that I think it is nicely representative of the application.

**Review by metsma — APPROVED** [review]

**Comment by minosimo** [comment]
Do you have some idea when the next release would be, and might it be possible to get a version number bump with just the changes from this MR included? Again, for distros that package digidoc this would be a huge help, as it would allow the application to show up in graphical package managers / "software centers".

**Pull request merged**
